apiVersion: v1
kind: Service
metadata:
  name: nginx-custom
  namespace: default        # <--- ajout important
  labels:
    app: nginx-custom
spec:
  type: NodePort
  selector:
    app: nginx-custom
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
